trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ./build-rocksdb.sh
    workingDirectory: '$(Build.SourcesDirectory)/build-native'

