trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:



- task: Bash@3
  inputs:
    filePath: '$(Build.SourcesDirectory)/build-native/build-rocksdb.sh'
    workingDirectory: '$(Build.SourcesDirectory)/build-native/'

