trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ROCKSDBVNUM=`cat rocksdbversion`
      echo "##vso[task.setvariable variable=ROCKSDBVERSION]${ROCKSDBVNUM}"
    workingDirectory: '$(Build.SourcesDirectory)'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      brew install automake
      brew install libtool
      git clone https://github.com/google/snappy
      cd snappy
      ./autogen.sh
      ./configure --prefix=/usr/local CFLAGS="-arch i386 -arch x86_64" CXXFLAGS="-arch i386 -arch x86_64" LDFLAGS="-arch i386 -arch x86_64" --disable-dependency-tracking
      make
      sudo make install
    workingDirectory: '$(Build.SourcesDirectory)'

- task: Bash@3
  inputs:
    filePath: '$(Build.SourcesDirectory)/build-native/build-rocksdb.sh'
    workingDirectory: '$(Build.SourcesDirectory)/build-native/'

- task: CmdLine@2
  inputs:
    script: 'ls $(Build.SourcesDirectory) -hR'
  
- task: AzureCLI@1
  inputs:
    azureSubscription: 'Pay-As-You-Go(df68d6af-9145-400b-9276-6a84ca4dec2b)'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload -f $(Build.SourcesDirectory)/build-native/runtimes/osx-x64/native/librocksdb.dylib --account-name curiositydev  -c rocksdb  -n librocksdb-v$(ROCKSDBVERSION).dylib'