trigger:
- master

variables:
  HOMEBREW_CELLAR: /usr/local/Cellar/

pool:
  vmImage: 'macOS-latest'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ROCKSDBVNUM=`cat rocksdbversion`
      echo "##vso[task.setvariable variable=ROCKSDBVERSION]${ROCKSDBVNUM}"
    workingDirectory: '$(Build.SourcesDirectory)'

- task: CmdLine@2
  displayName: 'list brew folder'
  inputs:
    script: 'ls -hR $(HOMEBREW_CELLAR)'

- task: Bash@3
  inputs:
    filePath: '$(Build.SourcesDirectory)/build-native/build-rocksdb.sh'
    workingDirectory: '$(Build.SourcesDirectory)/build-native/'

- task: CmdLine@2
  displayName: 'list build folder'
  inputs:
    script: 'ls $(Build.SourcesDirectory)'
    
- task: CmdLine@2
  displayName: 'list brew folder after'
  inputs:
    script: 'ls -hR $(HOMEBREW_CELLAR)'    
  
- task: AzureCLI@1
  inputs:
    azureSubscription: 'Pay-As-You-Go(df68d6af-9145-400b-9276-6a84ca4dec2b)'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload -f $(Build.SourcesDirectory)/build-native/runtimes/osx-x64/native/librocksdb.dylib --account-name curiositydev  -c rocksdb  -n librocksdb-v$(ROCKSDBVERSION).dylib'
    
    

- task: AzureCLI@1
  inputs:
    azureSubscription: 'Pay-As-You-Go(df68d6af-9145-400b-9276-6a84ca4dec2b)'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload -f "$(HOMEBREW_CELLAR)/zlib/1.2.11/lib/libz.dylib" --account-name curiositydev  -c rocksdb  -n libz-v$(ROCKSDBVERSION).dylib'    
    
    
- task: AzureCLI@1
  inputs:
    azureSubscription: 'Pay-As-You-Go(df68d6af-9145-400b-9276-6a84ca4dec2b)'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload -f "$(HOMEBREW_CELLAR)/lz4/1.9.3/lib/liblz4.dylib" --account-name curiositydev  -c rocksdb  -n liblz4-v$(ROCKSDBVERSION).dylib'    
    
- task: AzureCLI@1
  inputs:
    azureSubscription: 'Pay-As-You-Go(df68d6af-9145-400b-9276-6a84ca4dec2b)'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload -f "$(HOMEBREW_CELLAR)/snappy/1.1.9/lib/libsnappy.dylib" --account-name curiositydev  -c rocksdb  -n libsnappy-v$(ROCKSDBVERSION).dylib'    
    
- task: AzureCLI@1
  inputs:
    azureSubscription: 'Pay-As-You-Go(df68d6af-9145-400b-9276-6a84ca4dec2b)'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload -f "$(HOMEBREW_CELLAR)/zstd/1.5.0/lib/libzstd.dylib" --account-name curiositydev  -c rocksdb  -n libzstd-v$(ROCKSDBVERSION).dylib'    
    
